input_csv: data/cities.csv
output_csv: data/cities_restaurants.csv
agent: autonomous
model:
  provider: openai
  name: gpt-4o-mini
query_col: city
search:
  engine: duckduckgo
  results: 20
mcpServers:
  - name: google-maps
    command: npx
    args:
      - "-y"
      - "@modelcontextprotocol/server-google-maps"
prompt:
  system: You are an expert researcher who excels at using Google Maps.
  user: |
    # Instructions

    Use the maps tools you have access to to find the best restaurant in the city of {{city}}.
structure:
  restaurant_name:
    type: str
    description: The name of the restaurant.
  address:
    type: str
    description: The address of the restaurant.